cityenergyproject/dc

README.md
src/app/collections/city_buildings.js
src/app/router.js
src/app/templates/layout/landing-cards.html
src/app/templates/layout/landing.html
src/app/views/layout/landing.js
src/app/views/map/building_layer.js
src/index.html
src/styles/base/_variables.scss
src/styles/main/_index.scss
src/styles/main/_landing.scss
src/styles/main/_layout.scss

- added new landing page
- improved README file
- fixed mobile view
- fixed cards date

feat: DWEM-1 Add new landing page

---

src/app/views/layout/landing.js
src/styles/main/_layout.scss

fix: DWEM-1 Fix bug with unscrolled map

---

src/app/views/layout/landing.js

https://dcra-marketplace.atlassian.net/browse/DWEM-18?focusedCommentId=10026

feat: DWEM-18 Fix title

---

src/app/templates/layout/footer.html

https://dcra-marketplace.atlassian.net/browse/DWEM-23

feat: DWEM-23 add new download link

---

src/app/views/layout/landing.js

https://dcra-marketplace.atlassian.net/browse/DWEM-16
Fixed histogram x line

fix: DWEM-16 Fixed histogram x line

---

src/app/views/layout/landing.js

add new Total Energy Consumption formula
https://dcra-marketplace.atlassian.net/browse/DWEM-26

DWEM-26 add new Total Energy Consumption formula

---

src/app/views/layout/landing.js

fix: DWEM-16 fix edge case in Safari

---

src/app/router.js
src/app/templates/layout/building_counts.html
src/app/templates/layout/compare_bar.html
src/app/templates/map_controls/filter_building_details.html
src/app/templates/map_controls/filter_container.html
src/app/templates/map_controls/filter_property_type.html
src/app/templates/map_controls/filter_quartile.html
src/app/templates/map_controls/filter_section_header.html
src/app/views/charts/histogram.js
src/app/views/layout/building_counts.js
src/app/views/layout/compare_bar.js
src/app/views/layout/footer.js
src/app/views/map/filter.js
src/app/views/map/map.js
src/index.html
src/styles/base/_variables.scss
src/styles/main/_building_counts.scss
src/styles/main/_compare_bar.scss
src/styles/main/_filter.scss
src/styles/main/_footer.scss
src/styles/main/_index.scss
src/styles/main/_landing.scss

Add new Building comparison functionality
https://dcra-marketplace.atlassian.net/browse/DWEM-3

feat: DWEM-3 Add new Building comparison functionality

---

src/app/collections/city_buildings.js
src/app/router.js
src/cities/dc.json

Fix: DWEM-21 fix sql query

---

src/app/views/map/building_layer.js
src/cities/dc.json

Feat: DWEM-6 enable footprints

---

src/app/views/layout/landing.js

fix: DWEM-27 - correct submission calculation

---

src/styles/main/_landing.scss

https://dcra-marketplace.atlassian.net/browse/DWEM-30

fix: DWEM-30 fix style for landing

---

src/styles/main/_filter.scss

https://dcra-marketplace.atlassian.net/browse/DWEM-34

fix: DWEM-34 fix color

---

src/cities/dc.json

https://dcra-marketplace.atlassian.net/browse/DWEM-33

DWEM-33 Change beps colors

---

src/app/views/map/building_layer.js
src/cities/dc.json

https://dcra-marketplace.atlassian.net/browse/DWEM-35

DWEM-35 Fix popup for footprints

---

src/cities/dc.json

https://dcra-marketplace.atlassian.net/browse/DWEM-37

DWEM-37 Fix property size

---

src/app/views/map/building_layer.js
src/cities/dc.json

https://dcra-marketplace.atlassian.net/browse/DWEM-38

DWEM-38 Fix electricity_grid_use filter

---

src/styles/main/_filter.scss

DWEM-32: Fix background for compare closer

---

src/app/views/layout/compare_bar.js

https://dcra-marketplace.atlassian.net/browse/DWEM-41

DWEM-41 Fix empty name for compare bar

---

src/app/views/map/building_layer.js

https://dcra-marketplace.atlassian.net/browse/DWEM-38?focusedCommentId=10117

DWEM-38 part2 fix add to compare after slct adrr

---

src/cities/dc.json

Fix: DWEM-36 Change filter name for water based energy use

---

src/app/models/scorecard.js
src/app/templates/scorecards/building.html
src/app/templates/scorecards/scorecard.html
src/app/views/scorecards/building_scorecard.js
src/app/views/scorecards/charts/comments.js
src/app/views/scorecards/controller.js

https://dcra-marketplace.atlassian.net/browse/DWEM-5?focusedCommentId=10111

DWEM-5 Change in scorecard

---

src/app/views/map/building_layer.js
src/cities/dc.json

https://dcra-marketplace.atlassian.net/browse/DWEM-42

DWEM-42 popup_fields support array in field section

---

src/app/templates/map/building_info.html

https://dcra-marketplace.atlassian.net/browse/DWEM-45

DWEM-45 rename to View Building Scorecard

---

src/cities/dc.json

https://dcra-marketplace.atlassian.net/browse/DWEM-44

DWEM-44 Implement ui changes

---

src/app/templates/scorecards/building.html
src/app/views/scorecards/building_scorecard.js

Fix: DWEM-49 replace id with pm id in scorecard

---

src/app/templates/scorecards/scorecard.html
src/app/views/scorecards/controller.js

Fix: DWEM-47 add button to print scorecard

---

src/styles/main/_filter.scss

fix:DWEM-43 - fix style issues

---

src/app/templates/scorecards/building.html
src/app/views/scorecards/building_scorecard.js

Feat: DWEM-50 Use zip in address on scorecard

---

src/app/templates/scorecards/building.html
src/app/views/scorecards/building_scorecard.js

Fix: DWEM-50 use postal code properly for address

---

src/app/templates/scorecards/building.html
src/app/templates/scorecards/scorecard.html
src/styles/main/_layout.scss

Fix: DWEM-47 fix scorecard print version

---

src/app/views/scorecards/building_scorecard.js

Fix: DWEM-48 use weather norm site eui on scorecard

---

src/app/views/scorecards/building_scorecard.js

Fix: DWEM-48 fix error when there are no thresholds

---

src/app/views/map/address_search_autocomplete.js

Feat: DWEM-42 extend search for buildings

---

src/app/views/scorecards/building_scorecard.js

Fix: DWEM-48 use proper column for eui on scorecard

---

src/app/views/scorecards/charts/fueluse.js

Fix: DWEM-48 replace mock w real data for fuel charts

---

src/app/views/map/year_control.js
src/styles/main/_building_counts.scss

https://dcra-marketplace.atlassian.net/browse/DWEM-3?focusedCommentId=10161

DWEM-3 Cleanup compare bar when year chaged

---

src/app/views/scorecards/building_scorecard.js

REMOVE MOCK

---

src/app/views/map/year_control.js

https://dcra-marketplace.atlassian.net/browse/DWEM-5?focusedCommentId=10176

DWEM-5 close popup

---

src/cities/dc.json

https://dcra-marketplace.atlassian.net/browse/DWEM-48?focusedCommentId=10175

DWEM-48 Change avg field

---

src/app/templates/scorecards/building.html
src/app/views/scorecards/building_scorecard.js
src/styles/main/_scorecard.scss

merge and deploy AS SOON AS  POSSIBLE

Fixed bug from master branch
